[package]
name = "clash-verge-service"
version = "1.0.0"
edition = "2021"
authors = ["zzzgydi", "Clash Verge Rev Team"]
license = "GPL-3.0"
repository = "https://github.com/zzzgydi/clash-verge-service.git"

[[bin]]
name = "clash-verge-service"
path = "src/main.rs"

[[bin]]
name = "prepare-service"
path = "src/prepare.rs"

[dependencies]
warp = "0.3"
anyhow = "1.0"
log = "0.4"
log4rs = "1.3"
once_cell = "1.19"
serde_json = "1.0"
parking_lot = "0.12"
windows-service = "0.7.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.31.4"
nix = "0.26"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target_os = "macos")'.dependencies]
interfaces = "0.0.9"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
